### ISSUE TITLE
premature close on unpack

### ISSUE THREAD

**Issue by walkabout21** [instructure/canvas-data-cli#20] opened 2019-09-26 16:38 UTC
### Description ###

Able to fetch compressed table data without issue.  When attempting to unpack the file is partially unpacked and then closes prematurely.  The resulting file is valid but missing the last 10 percent of the data.

`canvasDataCli unpack -c $canvas_path/config.js -f learning_outcome_dim -l debug`

### Additional Information ###
* canvas cli tool version 0.6.2
* Node Version 8.16.1
* Platform: Ubuntu 19.04
* Logs: 

```
will unpack learning_outcome_dim
outputting learning_outcome_dim to /media/acura/DEV/canvas/unpackedfiles/learning_outcome_dim.txt
an error occured
Error: premature close
    at MultiStream.onclose (/usr/lib/node_modules/canvas-data-cli/node_modules/end-of-stream/index.js:47:89)
    at MultiStream.emit (events.js:203:15)
    at MultiStream.destroy (/usr/lib/node_modules/canvas-data-cli/node_modules/multistream/index.js:65:8)
    at MultiStream._gotNextStream (/usr/lib/node_modules/canvas-data-cli/node_modules/multistream/index.js:94:10)
    at MultiStream._next (/usr/lib/node_modules/canvas-data-cli/node_modules/multistream/index.js:85:10)
    at Readable.onEnd (/usr/lib/node_modules/canvas-data-cli/node_modules/multistream/index.js:120:10)
    at Object.onceWrapper (events.js:286:20)
    at Readable.emit (events.js:198:13)
    at endReadableNT (/usr/lib/node_modules/canvas-data-cli/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Error: premature close
    at MultiStream.onclose (/usr/lib/node_modules/canvas-data-cli/node_modules/end-of-stream/index.js:47:89)
    at MultiStream.emit (events.js:203:15)
    at MultiStream.destroy (/usr/lib/node_modules/canvas-data-cli/node_modules/multistream/index.js:65:8)
    at MultiStream._gotNextStream (/usr/lib/node_modules/canvas-data-cli/node_modules/multistream/index.js:94:10)
    at MultiStream._next (/usr/lib/node_modules/canvas-data-cli/node_modules/multistream/index.js:85:10)
    at Readable.onEnd (/usr/lib/node_modules/canvas-data-cli/node_modules/multistream/index.js:120:10)
    at Object.onceWrapper (events.js:286:20)
    at Readable.emit (events.js:198:13)
    at endReadableNT (/usr/lib/node_modules/canvas-data-cli/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```
[community_link]: https://community.canvaslms.com/community/answers/data

**Comment by walkabout21** [comment] 2019-09-26 18:18
same issue on redhat server Red Hat Enterprise Linux 7.7

**Comment by walkabout21** [comment] 2019-09-26 18:18
Issue can't be reproduced on a windows build

**Comment by walkabout21** [comment] 2019-09-27 13:02
correction:  npm version given above.  nodejs version tested with stable 10 and latest 12

**Comment by walkabout21** [comment] 2019-09-30 20:08
This appears to be a problem with the schema.json file formatting.  I ran fixjson syntax fixer on the file and the unpack completes successfully on the ubuntu machine.

**Comment by walkabout21** [comment] 2019-09-30 20:12
ran fixjson on file and now completes without error on redhat server

**Comment by csunitdata** [comment] 2019-10-14 22:35
same error on windows desktop!!!
```

an error occured
Error: premature close
    at onclosenexttick (%home%\npm\node_modules\canvas-data-cli\node_modules\end-of-stream\index.js:53:86)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
Error: premature close
    at onclosenexttick (%home%\npm\node_modules\canvas-data-cli\node_modules\end-of-stream\index.js:53:86)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

```
```
%home%\npm>node -v
v12.12.0

%home%\npm>npm -v
6.11.3
```

I tried running the ./datafiles/schema.json in [fixjson](http://www.fixjson.com/) and still the issue exists. please suggest the fix

**Comment by csunitdata** [comment] 2019-10-15 00:39
even "Sync" command got following error:
```
downloaded 821 new files out of 3346 total files
2525 files failed to download, please try running the sync again, if this error persists, open a ticket. No files will be cleaned up
[
  {
    error: Error: max number of retries reached for requests-00022-68ed279c.gz, aborting
        at %home%\npm\node_modules\canvas-data-cli\lib\FileDownloader.js:52:18
        at Timeout._onTimeout (%home%\npm\node_modules\canvas-data-cli\node_modules\re\lib\re.js:90:43)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7),
    table: 'requests',
    filename: 'requests-00022-68ed279c.gz'
  },
```

**Comment by walkabout21** [comment] 2019-10-29 14:04
Any resolution here?  This issue started up again and the original resolution of formatting the schema file is not working

**Comment by iorabi** [comment] 2019-10-29 18:07
@walkabout21 I'm having the same issue running in a node alpine docker container. I've tried with node 8, 10, and 12.

**Comment by k-shelt** [comment] 2019-10-31 00:51
I'm also having the issue with windows.

**Comment by dlecocq** [comment] 2019-11-04 22:15
Hi all - just wanted to let you know that we're looking into it. We had an internal issue search that was broken, which is why we're only seeing this issue now :-/

**Comment by dlecocq** [comment] 2019-11-05 17:21
As far as I can tell, it's caused by a transitive dependency, `end-of-stream`. When pinned to version 1.4.1, everything works. However, versions 1.4.2-1.4.4 (the first of which was released three days before this issue was reported) cause this issue. I'm putting out a CR for it now.

**Comment by dlecocq** [comment] 2019-11-07 23:10
Hi all - if you install `canvas-data-cli@0.6.4`, the problem should be fixed. Please let us know if you experience continued issues after upgrading.

**Closed** 2023-06-16 11:41 UTC
